# Generated by Django 4.2.24 on 2025-09-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionweb1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='consulta1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartment_id', models.CharField(max_length=100)),
                ('cve_reference', models.CharField(max_length=100)),
                ('host_count', models.PositiveSmallIntegerField()),
                ('idv', models.CharField(max_length=100)),
                ('lifecycle_state', models.CharField(max_length=100)),
                ('name_cve', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('time_first_detected', models.CharField(max_length=30)),
                ('time_last_detected', models.CharField(max_length=30)),
                ('vulnerability_type', models.CharField(max_length=50)),
            ],
        ),
    ]
