# Generated by Django 4.2.24 on 2025-09-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionweb1', '0002_consulta1'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVulnerabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentication', models.CharField(max_length=30)),
                ('compartment_id', models.CharField(max_length=100)),
                ('cve_description', models.CharField(max_length=500)),
                ('cve_reference', models.CharField(max_length=30)),
                ('cvss3', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('exploitable', models.CharField(max_length=30)),
                ('impact', models.CharField(max_length=30)),
                ('patchable', models.CharField(max_length=50)),
                ('reference_url', models.CharField(max_length=50)),
                ('related_cve_reference', models.CharField(max_length=50)),
                ('solution', models.CharField(max_length=50)),
                ('threat', models.CharField(max_length=50)),
                ('time_published', models.CharField(max_length=50)),
                ('time_updated', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=30)),
                ('idvulnerabilidad', models.CharField(max_length=80)),
                ('impacted_resources_host_count', models.PositiveSmallIntegerField()),
                ('impacted_resources_image_count', models.PositiveSmallIntegerField()),
                ('lifecycle_state', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('time_first_detected', models.CharField(max_length=50)),
                ('time_last_detected', models.CharField(max_length=50)),
                ('vulnerability_reference', models.CharField(max_length=50)),
                ('vulnerability_type', models.CharField(max_length=20)),
            ],
        ),
    ]
