# Generated by Django 4.2.24 on 2025-09-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionweb1', '0003_detallevulnerabilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallevulnerabilidad',
            name='cvss3',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
