# Generated by Django 4.2.24 on 2025-09-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionweb1', '0005_alter_detallevulnerabilidad_exploitable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallevulnerabilidad',
            name='cve_description',
            field=models.CharField(max_length=100),
        ),
    ]
