# Generated by Django 4.2.24 on 2025-09-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionweb1', '0006_alter_detallevulnerabilidad_cve_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallevulnerabilidad',
            name='cve_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detallevulnerabilidad',
            name='description',
            field=models.TextField(),
        ),
    ]
