# Generated by Django 4.2.24 on 2025-09-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionweb1', '0007_alter_detallevulnerabilidad_cve_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallevulnerabilidad',
            name='idvulnerabilidad',
            field=models.CharField(max_length=100),
        ),
    ]
