# Generated by Django 4.2.24 on 2025-09-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionweb1', '0008_alter_detallevulnerabilidad_idvulnerabilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraficaVulnerabilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_vuln_riesgo', models.PositiveSmallIntegerField()),
                ('nombre_riesgo_vuln', models.CharField(max_length=30)),
            ],
        ),
    ]
